#!/bin/bash

python3 -m virtualenv /opt/shakenfist
if [ ! -e /opt/shakenfist ]; then
    if [ $(echo "ubuntu,debian" | grep -c "${DISTRO_NAME}") -gt 0 ]; then
        # Ubuntu 18.04 and Debian 10 require a different module to build
        # venvs, and some additional packages.
        apt-get install -y python3-venv python3-dev
        python3 -m venv --system-site-packages /opt/shakenfist
    fi
fi

DIB_SF_AGENT_PACKAGE=${DIB_SF_AGENT_PACKAGE:-shakenfist-agent}
/opt/shakenfist/bin/pip install ${DIB_SF_AGENT_PACKAGE}

cat - > /etc/systemd/system/sf-agent.service << EOF
[Unit]
Description=Shaken Fist minimal cloud in guest agent
After=network.target remote-fs.target nss-lookup.target

[Service]
Type=simple
User=root
Group=root

ExecStart=/bin/sh -c '/opt/shakenfist/bin/sf-agent daemon run'

Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable sf-agent
