#!/bin/bash

echo "==================="
echo "Setting up sf-agent"
echo "==================="

if [ $(echo "buster,xenial,bionic" | grep -c "${DIB_RELEASE}") -gt 0 ]; then
     # The packaged version of psutil on Debian 10 is so old we have to
     # compile our own.
     apt-get install -y build-essential python3-dev
fi

python3 -m virtualenv --system-site-packages /opt/shakenfist

set -x
if [ ! -e /opt/shakenfist ]; then
    if [ $(echo "ubuntu,debian" | grep -c "${DISTRO_NAME}") -gt 0 ]; then
        # Ubuntu 18.04 and Debian 10 require a different module to build
        # venvs, and some additional packages.
        apt-get install -y python3-venv python3-dev python3-pip
        python3 -m venv --system-site-packages /opt/shakenfist

        # This odd pip invocation is because older Ubuntu's sometimes
        # doesn't create a pip symlink in the venv. So, we use the module
	# to install a newer pip. The version pin is because pip 21+
	# doesn't support python 3.5, and we're in ancient python land
	# here.
        /opt/shakenfist/bin/python -m pip install -U "pip<21.0"
    fi
fi

DIB_SF_AGENT_PACKAGE=${DIB_SF_AGENT_PACKAGE:-shakenfist-agent}
/opt/shakenfist/bin/pip install ${DIB_SF_AGENT_PACKAGE}

cat - > /etc/systemd/system/sf-agent.service << EOF
[Unit]
Description=Shaken Fist minimal cloud in guest agent
After=network.target remote-fs.target nss-lookup.target

[Service]
Type=simple
User=root
Group=root

ExecStart=/bin/sh -c '/opt/shakenfist/bin/sf-agent daemon run'

Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable sf-agent

set +x
